# Generated by Django 5.1.7 on 2025-05-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("genre", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("rating", models.DecimalField(decimal_places=1, max_digits=3)),
                ("watched", models.BooleanField(default=False)),
            ],
        ),
    ]
